# Use official Node image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files first for cache optimization
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Build Angular project
RUN npm run build

# Install static server to serve build output
RUN npm install -g serve

# Set entrypoint (CMD is sufficient here for Angular)
CMD ["serve", "-s", "dist/food-advisor-f/browser", "-l", "4200"]

# Expose port
EXPOSE 4200
