# Use official Node image
FROM node:20 as builder

# Set working directory
WORKDIR /app

# Copy package files first for cache optimization
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Build Angular project
RUN npm run build

FROM caddy:alpine
COPY --from=builder /app/dist/food-advisor-f/browser /usr/share/caddy
